# Generated by Django 5.0.6 on 2024-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporty',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
